apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weather-api
  name: weather-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather-api
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/learned-pact-351114/poc-docker-repo-we/custom-weather-api-img:v1
        name: weather-api
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: weather-api
  labels:
    run: weather-api
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: weather-api
  type: LoadBalancer